#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env"
EXAMPLE_ENV="$ROOT_DIR/config/example.env"
COMPOSE_FILE="$ROOT_DIR/deploy/docker-compose.yml"
BACKUP_DIR="$ROOT_DIR/.vps-sentinel/backups"

START_BACKEND=false
START_FRONTEND=false
START_AGENT_PLACEHOLDER=false
PRINT_AGENT_COMMAND=false
ROLLBACK=false
CREATE_NETWORK=false

usage() {
  cat <<'USAGE'
Usage:
  ./deploy/install.sh [options]

Options:
  --start-backend             Start Komari backend profile after preparation
  --with-frontend             Start optional frontend preview profile
  --with-agent-placeholder    Start disabled placeholder container only
  --print-agent-command       Print a safe manual tcpping install command template
  --create-network            Create the configured external Docker network when absent
  --rollback                  Stop platform containers and restore previous compose backup
  -h, --help                  Show this help

Defaults:
  - Pull/check pinned source references
  - Generate .env when absent
  - Check whether the external Docker network exists
  - Pull pinned Komari image
  - Do not start agent
  - Do not modify firewall/system SSH configuration
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --start-backend)
      START_BACKEND=true
      ;;
    --with-frontend)
      START_FRONTEND=true
      ;;
    --with-agent-placeholder)
      START_AGENT_PLACEHOLDER=true
      ;;
    --print-agent-command)
      PRINT_AGENT_COMMAND=true
      ;;
    --create-network)
      CREATE_NETWORK=true
      ;;
    --rollback)
      ROLLBACK=true
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
  shift
done

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Missing required command: $1" >&2
    exit 1
  }
}

compose_cmd() {
  if docker compose version >/dev/null 2>&1; then
    docker compose --project-directory "$ROOT_DIR" "$@"
  elif command -v docker-compose >/dev/null 2>&1; then
    docker-compose --project-directory "$ROOT_DIR" "$@"
  else
    echo "Docker Compose is required. Install docker compose plugin or docker-compose." >&2
    exit 1
  fi
}

load_env() {
  if [ ! -f "$ENV_FILE" ]; then
    cp "$EXAMPLE_ENV" "$ENV_FILE"
    echo "Created .env from config/example.env"
  fi
  # shellcheck disable=SC1090
  set -a
  . "$ENV_FILE"
  set +a
}

backup_compose() {
  mkdir -p "$BACKUP_DIR"
  cp "$COMPOSE_FILE" "$BACKUP_DIR/docker-compose.$(date +%Y%m%d%H%M%S).yml"
}

restore_latest_compose() {
  latest="$(find "$BACKUP_DIR" -type f -name 'docker-compose.*.yml' 2>/dev/null | sort | tail -n 1 || true)"
  if [ -n "${latest:-}" ]; then
    cp "$latest" "$COMPOSE_FILE"
    echo "Restored compose file from $latest"
  else
    echo "No compose backup found; compose file left unchanged."
  fi
}

rollback() {
  need_cmd docker
  load_env
  echo "Stopping platform containers; data volumes/directories are preserved."
  compose_cmd --env-file "$ENV_FILE" -f "$COMPOSE_FILE" --profile backend --profile frontend --profile agent down --remove-orphans || true
  restore_latest_compose
  echo "Rollback finished. Data directory was not deleted."
}

clone_or_update() {
  name="$1"
  repo="$2"
  ref="$3"
  commit="$4"
  dest="$ROOT_DIR/${SOURCE_DIR:-./sources}/$name"

  mkdir -p "$(dirname "$dest")"

  if [ ! -d "$dest/.git" ]; then
    git clone "$repo" "$dest"
  fi

  git -C "$dest" fetch --tags origin

  case "$name" in
    komari-web)
      git -C "$dest" fetch origin "$ref"
      git -C "$dest" checkout --detach "$commit"
      ;;
    *)
      git -C "$dest" checkout --detach "$ref"
      ;;
  esac

  actual="$(git -C "$dest" rev-parse HEAD)"
  if [ "$actual" != "$commit" ]; then
    echo "Version check failed for $name: expected $commit, got $actual" >&2
    exit 1
  fi

  echo "$name pinned at $actual"
}

print_agent_command() {
  cat <<'COMMAND'
Safe agent manual install template:

curl -fsSL https://raw.githubusercontent.com/suckdrygod/tcpping/main/install.sh | sudo bash -s -- \
  -e https://agent.example.com \
  -t YOUR_NODE_TOKEN \
  --month-rotate 0 \
  --ssh-auth-guard \
  --ssh-auth-silent-mode \
  --ssh-auth-aggregate-by-ip \
  --ssh-auth-threshold 5 \
  --ssh-auth-window 60 \
  --ssh-auth-cooldown 1800

Notes:
- Replace endpoint and token with values generated by your own panel.
- Auto-ban is intentionally NOT enabled in this template.
- Do not add --ssh-auth-auto-ban unless you have confirmed whitelist and nftables behavior.
COMMAND
}

if [ "$ROLLBACK" = true ]; then
  rollback
  exit 0
fi

need_cmd git
need_cmd docker
load_env
backup_compose

mkdir -p "$ROOT_DIR/data/komari" "$ROOT_DIR/${SOURCE_DIR:-./sources}"

NETWORK_EXISTS=true
if ! docker network inspect "${VPS_SENTINEL_NETWORK:-vps-sentinel-external}" >/dev/null 2>&1; then
  NETWORK_EXISTS=false
fi

if [ "$NETWORK_EXISTS" = false ] && [ "$CREATE_NETWORK" = true ]; then
  docker network create "${VPS_SENTINEL_NETWORK:-vps-sentinel-external}" >/dev/null
  NETWORK_EXISTS=true
  echo "Created external Docker network: ${VPS_SENTINEL_NETWORK:-vps-sentinel-external}"
elif [ "$NETWORK_EXISTS" = true ]; then
  echo "External Docker network exists: ${VPS_SENTINEL_NETWORK:-vps-sentinel-external}"
else
  echo "External Docker network is missing: ${VPS_SENTINEL_NETWORK:-vps-sentinel-external}"
  echo "Create it manually, or rerun with --create-network when you are ready."
fi

clone_or_update "komari" "${KOMARI_REPO:-https://github.com/suckdrygod/komari.git}" "${KOMARI_REF:-1.2.5-tg.25}" "${KOMARI_COMMIT:-267e20922192afec4586886378df8661f2b9ec78}"
clone_or_update "tcpping" "${TCPPING_REPO:-https://github.com/suckdrygod/tcpping.git}" "${TCPPING_REF:-v1.2.13-safe.13}" "${TCPPING_COMMIT:-aa379696c97d9ad09eff82b0065a89cfa00ae3a0}"
clone_or_update "komari-web" "${KOMARI_WEB_REPO:-https://github.com/suckdrygod/komari-web.git}" "${KOMARI_WEB_REF:-radix}" "${KOMARI_WEB_COMMIT:-ea27b292360d0c0cc61c0ad66765a761e3d604cb}"

docker pull "${KOMARI_IMAGE:-ghcr.io/suckdrygod/komari:1.2.5-tg.25}"

profiles=()
if [ "$START_BACKEND" = true ]; then
  profiles+=(--profile backend)
fi
if [ "$START_FRONTEND" = true ]; then
  profiles+=(--profile frontend)
fi
if [ "$START_AGENT_PLACEHOLDER" = true ]; then
  profiles+=(--profile agent)
fi

if [ "${#profiles[@]}" -gt 0 ]; then
  if [ "$NETWORK_EXISTS" = false ]; then
    echo "Cannot start services because the external Docker network is missing." >&2
    echo "Run: docker network create ${VPS_SENTINEL_NETWORK:-vps-sentinel-external}" >&2
    exit 1
  fi
  compose_cmd --env-file "$ENV_FILE" -f "$COMPOSE_FILE" "${profiles[@]}" up -d
else
  echo "Preparation complete. No service was started by default."
fi

if [ "$PRINT_AGENT_COMMAND" = true ]; then
  print_agent_command
fi

cat <<EOF

Platform is ready.

Backend start command:
  ./deploy/install.sh --start-backend

Default backend URL:
  http://${KOMARI_HOST:-127.0.0.1}:${KOMARI_PORT:-25874}

Rollback command:
  ./deploy/install.sh --rollback
EOF
